"""SOC Agent persistence adapters."""

from soc_agent.db.base import SocBase, create_soc_tables
from soc_agent.db.config import resolve_database_url, to_sync_database_url
from soc_agent.db.effectiveness import SqlAlchemySocEffectivenessRepository
from soc_agent.db.migration_runner import upgrade_soc_schema
from soc_agent.db.models import (
    SocActionAuthorizationRow,
    SocActionExecutionRow,
    SocAlertSummaryRow,
    SocAnalysisRunRow,
    SocApprovalGrantRow,
    SocApprovalRequestRow,
    SocAuthorizationEnrichmentRow,
    SocDecisionAuditLogRow,
    SocDecisionTransitionRow,
    SocDispositionOutcomeRow,
    SocDispositionProposalRow,
    SocDispositionSampleManifestRow,
    SocDispositionTransitionRow,
    SocEnrichmentActionAttemptRow,
    SocEnrichmentExecutionRow,
    SocExternalDispositionRow,
    SocGovernedContextFactRow,
    SocInvestigationEvidenceRow,
    SocMemoryCandidateRow,
    SocMemoryPatternObservationRow,
    SocMemoryRecordFacetRow,
    SocMemoryRecordRow,
    SocMutationAuditRow,
    SocNormalizationMaintenanceIssueRow,
    SocNormalizationSchemaBaselineRow,
    SocReviewQueueRow,
    SocSkillFeedbackObservationRow,
    SocSkillImprovementCandidateRow,
    SocTenantPolicyDecisionRow,
)
from soc_agent.db.operations import SqlAlchemySocOperationsRepository
from soc_agent.db.repositories import SqlAlchemyAlertRepository

__all__ = [
    "SocAnalysisRunRow",
    "SocActionAuthorizationRow",
    "SocActionExecutionRow",
    "SocAuthorizationEnrichmentRow",
    "SocApprovalGrantRow",
    "SocApprovalRequestRow",
    "SocAlertSummaryRow",
    "SocDecisionAuditLogRow",
    "SocDecisionTransitionRow",
    "SocDispositionOutcomeRow",
    "SocDispositionProposalRow",
    "SocDispositionTransitionRow",
    "SocTenantPolicyDecisionRow",
    "SocDispositionSampleManifestRow",
    "SocEnrichmentActionAttemptRow",
    "SocEnrichmentExecutionRow",
    "SocExternalDispositionRow",
    "SocGovernedContextFactRow",
    "SocInvestigationEvidenceRow",
    "SocMemoryCandidateRow",
    "SocMemoryPatternObservationRow",
    "SocMemoryRecordRow",
    "SocMemoryRecordFacetRow",
    "SocMutationAuditRow",
    "SocNormalizationMaintenanceIssueRow",
    "SocNormalizationSchemaBaselineRow",
    "SocReviewQueueRow",
    "SocSkillFeedbackObservationRow",
    "SocSkillImprovementCandidateRow",
    "SocBase",
    "SqlAlchemyAlertRepository",
    "SqlAlchemySocEffectivenessRepository",
    "SqlAlchemySocOperationsRepository",
    "create_soc_tables",
    "resolve_database_url",
    "to_sync_database_url",
    "upgrade_soc_schema",
]
