"""PingAn-specific provider integrations.

Vendor field names, authentication mechanisms, and fallback workflows stop in
this package. Generic SOC Runtime and action services consume their typed
results through vendor-neutral routes such as ``asset.locate``.
"""

from soc_agent.integrations.pingan.asset_location import (
    CallablePingAnAssetWorkflowPort,
    HttpPingAnZeusAssetSearchPort,
    PingAnAssetLocationAttempt,
    PingAnAssetLocationCandidate,
    PingAnAssetLocationQuery,
    PingAnAssetLocationResult,
    PingAnAssetLocatorService,
    PingAnAssetOwnershipOverride,
    PingAnAssetProviderConfigurationError,
    PingAnAssetProviderError,
    PingAnAssetProviderUnavailableError,
    PingAnAssetType,
    PingAnAssetWorkflowConfig,
    StaticPingAnAssetSearchPort,
    StaticPingAnAssetWorkflowPort,
    build_pingan_asset_locator_from_env,
)
from soc_agent.integrations.pingan.d12b_acceptance import (
    PingAnAssetAttemptSummary,
    PingAnAssetCaseExecutionStatus,
    PingAnAssetCaseKind,
    PingAnAssetCaseMatrix,
    PingAnAssetCaseMatrixError,
    PingAnAssetCaseMatrixPlan,
    PingAnAssetCaseMatrixReport,
    PingAnAssetCaseMatrixStatus,
    PingAnAssetCaseResult,
    PingAnAssetCaseSpec,
    PingAnAssetExpectedAttempt,
    build_pingan_asset_case_matrix_plan,
    load_pingan_asset_case_matrix,
    run_pingan_asset_case_matrix,
)
from soc_agent.integrations.pingan.d12b_evidence_acceptance import (
    PingAnD12BEvidenceAcceptanceReport,
    PingAnD12BEvidenceAcceptanceStatus,
    PingAnD12BEvidenceCheck,
    PingAnD12BEvidenceCheckStatus,
    PingAnD12BEvidenceRepositoryPort,
    run_pingan_d12b_evidence_acceptance,
)
from soc_agent.integrations.pingan.software_path_catalog import (
    PINGAN_SOFTWARE_PATH_LOOKUP_ACTION,
    PingAnSoftwarePathCatalog,
    PingAnSoftwarePathCatalogBuildReport,
    PingAnSoftwarePathCatalogError,
    PingAnSoftwarePathContextResult,
    PingAnSoftwarePathLookupActionAdapter,
    classify_pingan_path,
    compile_pingan_software_path_catalog,
    normalize_windows_path,
)

__all__ = [
    "CallablePingAnAssetWorkflowPort",
    "HttpPingAnZeusAssetSearchPort",
    "PingAnAssetLocationAttempt",
    "PingAnAssetLocationCandidate",
    "PingAnAssetLocationQuery",
    "PingAnAssetLocationResult",
    "PingAnAssetLocatorService",
    "PingAnAssetOwnershipOverride",
    "PingAnAssetAttemptSummary",
    "PingAnAssetCaseExecutionStatus",
    "PingAnAssetCaseKind",
    "PingAnAssetCaseMatrix",
    "PingAnAssetCaseMatrixError",
    "PingAnAssetCaseMatrixPlan",
    "PingAnAssetCaseMatrixReport",
    "PingAnAssetCaseMatrixStatus",
    "PingAnAssetCaseResult",
    "PingAnAssetCaseSpec",
    "PingAnAssetExpectedAttempt",
    "PingAnD12BEvidenceAcceptanceReport",
    "PingAnD12BEvidenceAcceptanceStatus",
    "PingAnD12BEvidenceCheck",
    "PingAnD12BEvidenceCheckStatus",
    "PingAnD12BEvidenceRepositoryPort",
    "PingAnAssetProviderConfigurationError",
    "PingAnAssetProviderError",
    "PingAnAssetProviderUnavailableError",
    "PingAnAssetType",
    "PingAnAssetWorkflowConfig",
    "PINGAN_SOFTWARE_PATH_LOOKUP_ACTION",
    "PingAnSoftwarePathCatalog",
    "PingAnSoftwarePathCatalogBuildReport",
    "PingAnSoftwarePathCatalogError",
    "PingAnSoftwarePathContextResult",
    "PingAnSoftwarePathLookupActionAdapter",
    "StaticPingAnAssetSearchPort",
    "StaticPingAnAssetWorkflowPort",
    "build_pingan_asset_locator_from_env",
    "build_pingan_asset_case_matrix_plan",
    "classify_pingan_path",
    "compile_pingan_software_path_catalog",
    "load_pingan_asset_case_matrix",
    "normalize_windows_path",
    "run_pingan_asset_case_matrix",
    "run_pingan_d12b_evidence_acceptance",
]
